Update the list of existing libraries
beakerlib/libraries pull request #11
Opened 2023-05-25 15:41 UTC by psss

There are a few new libs, let's list them as well.

2023-05-26 08:27 UTC, hegerj requested changes

2023-05-26 08:27 UTC, hegerj commented on README.md
>  | [database/mariadb](https://github.com/beakerlib/database/tree/master/mariadb/) | Set of basic functions for mariadb | Lukas Zachar <lzachar@redhat.com> |
Could you please change responsible person to me for mariadb lib while you are making changes?

2023-05-29 07:57 UTC, hegerj commented on README.md
>  | [database/mariadb](https://github.com/beakerlib/database/tree/master/mariadb/) | Set of basic functions for mariadb | Lukas Zachar <lzachar@redhat.com> |
Oops, my bad, I fixed the contact.

2023-05-29 07:58 UTC, hegerj approved these changes

2023-05-30 08:06 UTC, psss commented on README.md
>  | [database/mariadb](https://github.com/beakerlib/database/tree/master/mariadb/) | Set of basic functions for mariadb | Lukas Zachar <lzachar@redhat.com> |
Thanks.

2023-05-30 08:06 UTC, merged